// AUTO-GENERATED from the frontend Pakistan geo dataset
// (Student-Smart-Card/src/data/pakistanGeo.js). Province codes are fixed;
// district codes are the district's 1-based position within its province.
// Used to build the structured 16-digit card number:
//   7727 (SSCP) + PP (province) + DD (district) + 8 random digits.
// Append new districts at the END of a province so existing codes never shift.

export const SSCP_PREFIX = '7727';

export const PROVINCE_CODES: Record<string, string> = {
  "Punjab": "72",
  "Sindh": "74",
  "Khyber Pakhtunkhwa": "76",
  "Balochistan": "78",
  "Islamabad Capital Territory": "61",
  "Azad Jammu & Kashmir": "82",
  "Gilgit-Baltistan": "84",
};

export const DISTRICT_CODES: Record<string, Record<string, string>> = {
  "Punjab": {
    "Lahore": "01",
    "Kasur": "02",
    "Nankana Sahib": "03",
    "Sheikhupura": "04",
    "Gujranwala": "05",
    "Gujrat": "06",
    "Hafizabad": "07",
    "Mandi Bahauddin": "08",
    "Narowal": "09",
    "Sialkot": "10",
    "Faisalabad": "11",
    "Chiniot": "12",
    "Jhang": "13",
    "Toba Tek Singh": "14",
    "Rawalpindi": "15",
    "Attock": "16",
    "Chakwal": "17",
    "Jhelum": "18",
    "Sargodha": "19",
    "Bhakkar": "20",
    "Khushab": "21",
    "Mianwali": "22",
    "Multan": "23",
    "Khanewal": "24",
    "Lodhran": "25",
    "Vehari": "26",
    "Dera Ghazi Khan": "27",
    "Layyah": "28",
    "Muzaffargarh": "29",
    "Rajanpur": "30",
    "Bahawalpur": "31",
    "Bahawalnagar": "32",
    "Rahim Yar Khan": "33",
    "Sahiwal": "34",
    "Okara": "35",
    "Pakpattan": "36",
  },
  "Sindh": {
    "Karachi East": "01",
    "Karachi West": "02",
    "Karachi Central": "03",
    "Karachi South": "04",
    "Malir": "05",
    "Korangi": "06",
    "Keamari": "07",
    "Hyderabad": "08",
    "Badin": "09",
    "Dadu": "10",
    "Jamshoro": "11",
    "Matiari": "12",
    "Tando Allahyar": "13",
    "Tando Muhammad Khan": "14",
    "Thatta": "15",
    "Sujawal": "16",
    "Sukkur": "17",
    "Ghotki": "18",
    "Khairpur": "19",
    "Shikarpur": "20",
    "Larkana": "21",
    "Jacobabad": "22",
    "Kashmore": "23",
    "Kambar Shahdadkot": "24",
    "Mirpur Khas": "25",
    "Tharparkar": "26",
    "Umerkot": "27",
    "Shaheed Benazirabad": "28",
    "Naushahro Feroze": "29",
    "Sanghar": "30",
  },
  "Khyber Pakhtunkhwa": {
    "Peshawar": "01",
    "Charsadda": "02",
    "Nowshera": "03",
    "Khyber": "04",
    "Mohmand": "05",
    "Mardan": "06",
    "Swabi": "07",
    "Abbottabad": "08",
    "Haripur": "09",
    "Mansehra": "10",
    "Battagram": "11",
    "Torghar": "12",
    "Lower Kohistan": "13",
    "Upper Kohistan": "14",
    "Swat": "15",
    "Shangla": "16",
    "Buner": "17",
    "Lower Dir": "18",
    "Upper Dir": "19",
    "Lower Chitral": "20",
    "Upper Chitral": "21",
    "Malakand": "22",
    "Bajaur": "23",
    "Kohat": "24",
    "Hangu": "25",
    "Karak": "26",
    "Orakzai": "27",
    "Bannu": "28",
    "Lakki Marwat": "29",
    "North Waziristan": "30",
    "Dera Ismail Khan": "31",
    "Tank": "32",
    "Lower South Waziristan": "33",
    "Upper South Waziristan": "34",
  },
  "Balochistan": {
    "Quetta": "01",
    "Pishin": "02",
    "Killa Abdullah": "03",
    "Kalat": "04",
    "Khuzdar": "05",
    "Mastung": "06",
    "Awaran": "07",
    "Lasbela": "08",
    "Kharan": "09",
    "Washuk": "10",
    "Gwadar": "11",
    "Kech (Turbat)": "12",
    "Panjgur": "13",
    "Nasirabad": "14",
    "Jafarabad": "15",
    "Jhal Magsi": "16",
    "Kachhi (Bolan)": "17",
    "Sohbatpur": "18",
    "Usta Muhammad": "19",
    "Sibi": "20",
    "Ziarat": "21",
    "Harnai": "22",
    "Kohlu": "23",
    "Dera Bugti": "24",
    "Zhob": "25",
    "Sherani": "26",
    "Killa Saifullah": "27",
    "Musakhel": "28",
    "Loralai": "29",
    "Barkhan": "30",
    "Duki": "31",
    "Chagai": "32",
    "Nushki": "33",
  },
  "Islamabad Capital Territory": {
    "Islamabad": "01",
  },
  "Azad Jammu & Kashmir": {
    "Muzaffarabad": "01",
    "Hattian Bala": "02",
    "Neelum": "03",
    "Poonch (Rawalakot)": "04",
    "Bagh": "05",
    "Haveli": "06",
    "Sudhanoti": "07",
    "Mirpur": "08",
    "Bhimber": "09",
    "Kotli": "10",
  },
  "Gilgit-Baltistan": {
    "Gilgit": "01",
    "Ghizer": "02",
    "Hunza": "03",
    "Nagar": "04",
    "Skardu": "05",
    "Shigar": "06",
    "Kharmang": "07",
    "Ghanche": "08",
    "Diamer (Chilas)": "09",
    "Astore": "10",
  },
};

export function provinceCode(province?: string | null): string {
  return (province && PROVINCE_CODES[province]) || '00';
}

export function districtCode(
  province?: string | null,
  district?: string | null,
): string {
  if (!province || !district) return '00';
  return DISTRICT_CODES[province]?.[district] ?? '00';
}
